ch_test:
  outputs:
    dev:
      dbname: postgres
      host: century-health-assignment.crq4aaeisjvp.us-east-1.rds.amazonaws.com
      pass: postgres123
      port: 5432
      schema: dbt
      threads: 1
      type: postgres
      user: postgres
  target: dev
